AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Handle the contact form submission from the public pages. A search against
  DynamoDB is required and if the user is found an email is sent to the profile
  email address.
Resources:
  contactform:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        Handle the contact form submission from the public pages. A search
        against DynamoDB is required and if the user is found an email is sent
        to the profile email address.
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::128225160927:role/service-role/ses-contact-form-lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /contact-form
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint
