(ns helodali.types)

;; styles taken from wpadc.org
(def styles
  (sorted-map
    :abstract "Abstract"
    :allegorical "Allegorical"
    :architecture "Architecture"
    :assemblage "Assemblage"
    :autobiographical "Autobiographical"
    :biomorphic "Biomorphic"
    :cartoonesque "Cartoonesque"
    :color-field "Color field"
    :conceptual "Conceptual"
    :constructed "Constructed"
    :decorative "Decorative"
    :didactic "Didactic"
    :documentary "Documentary"
    :domestic-family "Domestic/family"
    :environmental "Environmental"
    :erotic "Erotic"
    :expressionistic "Expressionistic"
    :fantasy "Fantasy"
    :feminist "Feminist"
    :figurative "Figurative"
    :functional "Functional"
    :futuristic "Futuristic"
    :gender-sexuality "Gender/sexuality"
    :geometric "Geometric"
    :hard-edge "Hard-edge"
    :humanist "Humanist"
    :humorous "Humorous"
    :illusionistic "Illusionistic"
    :impressionistic "Impressionistic"
    :interactive "Interactive"
    :ironic "Ironic"
    :kinetic "Kinetic"
    :kitsch "Kitsch"
    :landscape "Landscape"
    :light-reflective "Light reflective"
    :linear "Linear"
    :literary "Literary"
    :lyrical "Lyrical"
    :minimal "Minimal"
    :narrative "Narrative"
    :nudes "Nudes"
    :optical "Optical"
    :painterly "Painterly"
    :political "Political"
    :popular-imagery "Popular imagery"
    :portraits "Portraits"
    :primitivistic "Primitivistic"
    :process-oriented "Process oriented"
    :psychological "Psychological"
    :religious "Religious"
    :representational "Representational"
    :romantic "Romantic"
    :serial "Serial"
    :shaped-format "Shaped-format"
    :sociological "Sociological"
    :spiritual "Spiritual"
    :still-life "Still-life"
    :surreal "Surreal"
    :symbolic "Symbolic"
    :technological "Technological"
    :trompe-loeil "Trompe l'oeil"
    :urban "Urban"))

(def media
  (sorted-map
    :architecture "Architecture"
    :books "Books"
    :collage "Collage"
    :computer "Computer"
    :digital "Digital"
    :drawings "Drawings"
    :film-video "Film-Video"
    :installation "Installation"
    :mixed-media "Mixed-Media"
    :mural "Mural"
    :painting "Painting"
    :performance "Performance"
    :photography "Photography"
    :prints "Prints"
    :sculpture "Sculpture"
    :wall-relief "Wall-Relief"
    :works-on-paper "Works on paper"))